"""init

Revision ID: 481ae835bfa5
Revises: 
Create Date: 2019-05-29 17:02:52.339267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481ae835bfa5'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
